version: '3.4'

x-common-variables: &common-variables
    DB_DATABASE: 'inventory'
    DB_USERNAME: 'mern_docker' #Change this
    DB_PASSWORD: 'mern_docker' #Change this

services:
    # db:
    #     container_name: app_database
    #     image: mysql:8
    #     restart: always
    #     environment:
    #         <<: *common-variables
    #         DB_HOST: localhost
    #         MYSQL_ROOT_PASSWORD: 'mern_docker' #Change this
    #     volumes:
    #         - my-db-volume:/var/lib/mysql
    #     ports: 
    #         - 9906:3306

    backend:
        container_name: app_backend
        build:
            dockerfile: Dockerfile
            context: ./backend
        # depends_on:
        #     - db
        environment:
            <<: *common-variables
            DB_HOST_IP: db #Service name

    frontend:
        container_name: app_frontend
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./frontend

    reverse-proxy:
        container_name: app_proxy
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - 8080:80
        depends_on:
            - backend
            - frontend

# volumes:
#     my-db-volume: